# Generated by Django 4.2.3 on 2023-08-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reservadebanho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['data'], 'verbose_name': 'formulário de contato', 'verbose_name_plural': 'formulários de contatos'},
        ),
        migrations.RenameField(
            model_name='reservadebanho',
            old_name='telefone',
            new_name='telefone',
        ),
    ]
