# Generated by Django 4.2.3 on 2023-09-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contato_lido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadebanho',
            name='diadareserva',
            field=models.DateField(verbose_name='Dia da Reserva'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='nomedopet',
            field=models.CharField(max_length=50, verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name=' Telefone'),
        ),
    ]
